--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/oddstap/Pictures/Wallpaper/1604046084199.jpg"

-- Special
background="#090909"
foreground="#f4f4f4"
cursor="#f4f4f4"

-- Colors
color0="#090909"
color1="#909090"
color2="#B1B1B1"
color3="#C8C8C8"
color4="#D7D7D7"
color5="#E8E8E8"
color6="#F4F4F4"
color7="#f4f4f4"
color8="#aaaaaa"
color9="#909090"
color10="#B1B1B1"
color11="#C8C8C8"
color12="#D7D7D7"
color13="#E8E8E8"
color14="#F4F4F4"
color15="#f4f4f4"
