# Shell variables
# Generated by 'wal'
wallpaper="/home/oddstap/Pictures/Wallpaper/1604046084199.jpg"

# Special
background='#090909'
foreground='#f4f4f4'
cursor='#f4f4f4'

# Colors
color0='#090909'
color1='#909090'
color2='#B1B1B1'
color3='#C8C8C8'
color4='#D7D7D7'
color5='#E8E8E8'
color6='#F4F4F4'
color7='#f4f4f4'
color8='#aaaaaa'
color9='#909090'
color10='#B1B1B1'
color11='#C8C8C8'
color12='#D7D7D7'
color13='#E8E8E8'
color14='#F4F4F4'
color15='#f4f4f4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
